// <auto-generated />
namespace BugTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Nah : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nah));
        
        string IMigrationMetadata.Id
        {
            get { return "202602232208047_Nah"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
